org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

EASYUI_KEYSTORE_PATH=easyui-release.jks
EASYUI_KEYSTORE_PASSWORD=easyui123
EASYUI_KEY_ALIAS=easyui-key
EASYUI_KEY_PASSWORD=easyui123
